openapi: 3.0.0
info:
  description: This is an OpenAPI specification for the University Life Manager backend.
    Request/response objects can be specified in components. Endpoints can be specified
    in paths.
  title: University Life Manager API
  version: 1.0.0
servers:
- url: /api/v1
security:
- bearerAuth: []
paths:
  /course:
    post:
      operationId: course_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseInfo'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseInfo'
          description: Created
        "401":
          description: Credentials are missing or invalid
      summary: Create a new course for the user
      x-openapi-router-controller: ulmapi.controllers.impl.default_controller
  /course/{courseId}:
    put:
      operationId: course_course_id_put
      parameters:
      - description: Course ID
        explode: false
        in: path
        name: courseId
        required: true
        schema:
          pattern: '[a-z0-9]+'
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseInfo'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseInfo'
          description: Created
        "401":
          description: Credentials are missing or invalid
      summary: Update a course for the user
      x-openapi-router-controller: ulmapi.controllers.impl.default_controller
  /course/{courseId}/deliverable:
    post:
      operationId: course_course_id_deliverable_post
      parameters:
      - description: Course ID
        explode: false
        in: path
        name: courseId
        required: true
        schema:
          pattern: '[a-z0-9]+'
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeliverableInfo'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliverableInfo'
          description: Created
        "401":
          description: Credentials are missing or invalid
      summary: Create a new deliverable for the user's course
      x-openapi-router-controller: ulmapi.controllers.impl.default_controller
  /course/{courseId}/deliverable/{deliverableId}:
    put:
      operationId: course_course_id_deliverable_deliverable_id_put
      parameters:
      - description: Course ID
        explode: false
        in: path
        name: courseId
        required: true
        schema:
          pattern: '[a-z0-9]+'
          type: string
        style: simple
      - description: Deliverable ID (auto-generated on deliverable creation)
        explode: false
        in: path
        name: deliverableId
        required: true
        schema:
          pattern: '[a-z0-9]+'
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeliverableInfo'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliverableInfo'
          description: Created
        "401":
          description: Credentials are missing or invalid
      summary: Update a deliverable for the user's course
      x-openapi-router-controller: ulmapi.controllers.impl.default_controller
  /course/{courseId}/timespent:
    post:
      operationId: course_course_id_timespent_post
      parameters:
      - description: Course ID
        explode: false
        in: path
        name: courseId
        required: true
        schema:
          pattern: '[a-z0-9]+'
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimeSpentInfo'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeSpentInfo'
          description: Created
        "401":
          description: Credentials are missing or invalid
      summary: Create a new time spent for the user's course
      x-openapi-router-controller: ulmapi.controllers.impl.default_controller
  /login:
    post:
      operationId: login_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessToken'
          description: OK
        "401":
          description: Credentials are missing or invalid
      security: []
      summary: Exchange username and password for access token
      x-openapi-router-controller: ulmapi.controllers.impl.default_controller
  /schedule:
    post:
      operationId: schedule_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleInfo'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleInfo'
          description: Created
        "401":
          description: Credentials are missing or invalid
      summary: Request generation of a new schedule
      x-openapi-router-controller: ulmapi.controllers.impl.default_controller
  /signup:
    post:
      operationId: signup_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupInfo'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessToken'
          description: OK
        "400":
          description: A malformed request could not be processed, e.g. a field must
            be unique or non-empty but was not
      security: []
      summary: Creates a new user (signup)
      x-openapi-router-controller: ulmapi.controllers.impl.default_controller
  /user:
    get:
      operationId: user_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/UserInfo'
                type: array
          description: OK
        "400":
          description: A malformed request could not be processed, e.g. a field must
            be unique or non-empty but was not
        "401":
          description: Credentials are missing or invalid
        "404":
          description: Entity could not be found
      summary: Get user's information
      x-openapi-router-controller: ulmapi.controllers.impl.default_controller
components:
  responses:
    AuthorizationError:
      description: Credentials are missing or invalid
    BadRequest:
      description: A malformed request could not be processed, e.g. a field must be
        unique or non-empty but was not
    NotFoundError:
      description: Entity could not be found
  schemas:
    CourseInfo:
      example:
        expected_difficulty: 1
        course_id: course_id
        course_name: course_name
        deliverables:
          key:
            deliverable_id: deliverable_id
            grade: 14.658129805029452
            weight: 59.621339166831824
            due_at: 2000-01-23T04:56:07.000+00:00
            completed: true
            deliverable_name: deliverable_name
        desired_grade: 60
        time_spent:
        - notes: notes
          started_at: 2000-01-23T04:56:07.000+00:00
          ended_at: 2000-01-23T04:56:07.000+00:00
        - notes: notes
          started_at: 2000-01-23T04:56:07.000+00:00
          ended_at: 2000-01-23T04:56:07.000+00:00
      properties:
        course_id:
          minLength: 1
          pattern: '[a-z0-9]+'
          type: string
        course_name:
          minLength: 1
          type: string
        expected_difficulty:
          format: int32
          maximum: 5
          minimum: 1
          type: integer
        desired_grade:
          format: int32
          maximum: 100
          minimum: 0
          type: integer
        deliverables:
          additionalProperties:
            $ref: '#/components/schemas/DeliverableInfo'
          type: object
        time_spent:
          items:
            $ref: '#/components/schemas/TimeSpentInfo'
          type: array
      required:
      - course_id
      - course_name
      - desired_grade
      - expected_difficulty
      type: object
    DeliverableInfo:
      example:
        deliverable_id: deliverable_id
        grade: 14.658129805029452
        weight: 59.621339166831824
        due_at: 2000-01-23T04:56:07.000+00:00
        completed: true
        deliverable_name: deliverable_name
      properties:
        deliverable_id:
          minLength: 1
          pattern: '[a-z0-9]+'
          type: string
        deliverable_name:
          minLength: 1
          type: string
        grade:
          maximum: 100
          minimum: 0
          type: number
        weight:
          maximum: 100
          minimum: 0
          type: number
        due_at:
          format: date-time
          type: string
        completed:
          type: boolean
      required:
      - completed
      - deliverable_name
      - due_at
      - weight
      type: object
    TimeSpentInfo:
      example:
        notes: notes
        started_at: 2000-01-23T04:56:07.000+00:00
        ended_at: 2000-01-23T04:56:07.000+00:00
      properties:
        notes:
          minLength: 1
          type: string
        started_at:
          format: date-time
          type: string
        ended_at:
          format: date-time
          type: string
      required:
      - ended_at
      - notes
      - started_at
      type: object
    UserInfo:
      example:
        joined_at: 2000-01-23T04:56:07.000+00:00
        courses:
          key:
            expected_difficulty: 1
            course_id: course_id
            course_name: course_name
            deliverables:
              key:
                deliverable_id: deliverable_id
                grade: 14.658129805029452
                weight: 59.621339166831824
                due_at: 2000-01-23T04:56:07.000+00:00
                completed: true
                deliverable_name: deliverable_name
            desired_grade: 60
            time_spent:
            - notes: notes
              started_at: 2000-01-23T04:56:07.000+00:00
              ended_at: 2000-01-23T04:56:07.000+00:00
            - notes: notes
              started_at: 2000-01-23T04:56:07.000+00:00
              ended_at: 2000-01-23T04:56:07.000+00:00
        time_recorded:
          key: 6.027456183070403
        current_schedule:
          starts_at: 2000-01-23
          time_allocations:
            key: 0.8008281904610115
          ends_at: 2000-01-23
        email: email
        username: username
      properties:
        current_schedule:
          $ref: '#/components/schemas/UserInfo_current_schedule'
        time_recorded:
          additionalProperties:
            type: number
          type: object
        username:
          minLength: 1
          type: string
        email:
          minLength: 1
          type: string
        joined_at:
          format: date-time
          type: string
        courses:
          additionalProperties:
            $ref: '#/components/schemas/CourseInfo'
          type: object
      required:
      - email
      - username
      type: object
    UserCredentials:
      example:
        password: password
        username: username
      properties:
        username:
          type: string
        password:
          type: string
      required:
      - password
      - username
      type: object
    AccessToken:
      example:
        access_token: access_token
      properties:
        access_token:
          type: string
      required:
      - access_token
      type: object
    SignupInfo:
      example:
        password: password
        email: email
        username: username
      properties:
        email:
          minLength: 1
          type: string
        username:
          minLength: 1
          type: string
        password:
          minLength: 1
          type: string
      required:
      - email
      - password
      - username
      type: object
    ScheduleInfo:
      example:
        starts_at: 2000-01-23
        max_study_hours: 1
        time_allocations:
          key: 6.027456183070403
        ends_at: 2000-01-23
      properties:
        starts_at:
          format: date
          type: string
        ends_at:
          format: date
          type: string
        max_study_hours:
          format: int32
          minimum: 1
          type: integer
        time_allocations:
          additionalProperties:
            type: number
          type: object
      required:
      - ends_at
      - max_study_hours
      - starts_at
      type: object
    UserInfo_current_schedule:
      example:
        starts_at: 2000-01-23
        time_allocations:
          key: 0.8008281904610115
        ends_at: 2000-01-23
      properties:
        starts_at:
          format: date
          type: string
        ends_at:
          format: date
          type: string
        time_allocations:
          additionalProperties:
            type: number
          type: object
      type: object
  securitySchemes:
    bearerAuth:
      scheme: bearer
      type: http
      x-bearerInfoFunc: ulmapi.controllers.impl.security_controller_.info_from_bearerAuth
